import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Lobster } from "next/font/google";
import { Navbar } from "@/components/Navbar";

const lobster = Lobster({
  variable: "--font-lobster",
  weight: "400",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${lobster.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
